
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnzmhgvpynokshnlbsiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuem1oZ3ZweW5va3Nobmxic2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzI3NTUsImV4cCI6MjA1ODg0ODc1NX0.viIBr28yGeY9SaD9tYejkQ-5_Ihk69VygMYh6l-VThA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Extended User type that includes our custom fields
export interface ExtendedUser {
  id: string;
  email?: string;
  name?: string;
  avatar?: string;
  role?: string;
}

// Types for database entities
export type Property = {
  id: string;
  title: string;
  description?: string;
  price: number;
  location: string;
  address?: string;
  land_size?: number;
  building_size?: number;
  bedrooms?: number;
  bathrooms?: number;
  category: 'empty_lot' | 'semi_finished' | 'ready_to_occupy';
  status: 'available' | 'sold' | 'pending';
  featured: boolean;
  images?: string[];
  created_at: string;
  updated_at: string;
};

// Type for property managers
export type PropertyManager = {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  phone?: string;
  company: string;
  region: string;
  status: 'pending' | 'approved' | 'rejected';
  created_at: string;
  updated_at?: string;
};

// Type for testimonials
export type Testimonial = {
  id: string;
  name: string;
  avatar_url?: string;
  testimonial: string;
  rating: number;
  position?: string;
  company?: string;
  created_at: string;
};

// Type for inquiries
export type Inquiry = {
  id: string;
  user_id?: string;
  property_id?: string;
  name: string;
  email: string;
  phone?: string;
  message: string;
  status: string;
  created_at: string;
  updated_at: string;
};

// Helper type for dealing with tables that aren't in the TypeScript definitions yet
export type GenericTable = 'property_managers' | 'contents' | 'inquiries' | 'properties' | 
  'product_contents' | 'profiles' | 'saved_properties' | 'settings' | 
  'user_activities' | 'user_roles';
