// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eypyhmyltruvzigsuxod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cHlobXlsdHJ1dnppZ3N1eG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDc1NzUsImV4cCI6MjA2MDkyMzU3NX0.T75EF2nlZHJroPgE-frv1l2Q0PiHSJBJqvqWvNcNxOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Extended User type that includes our custom fields
export interface ExtendedUser {
  id: string;
  email?: string;
  name?: string;
  avatar?: string;
  role?: string;
}

// Types for database entities
export type Property = {
  id?: string;
  title: string;
  description?: string | null;
  price: number;
  location: string;
  address?: string | null;
  land_size?: number | null;
  building_size?: number | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  category: 'empty_lot' | 'semi_finished' | 'ready_to_occupy';
  status: 'available' | 'sold' | 'pending';
  featured: boolean;
  images?: string[] | null;
  created_at?: string;
  updated_at?: string;
  // Extended property fields
  floor_plan_images?: string[] | null;
  virtual_tour_url?: string | null;
  location_map_url?: string | null;
  meta_description?: string | null;
  features?: string[] | null;
  specifications?: Record<string, any> | null;
  faqs?: { question: string; answer: string }[] | null;
  amenities?: string[] | null;
  payment_options?: string[] | null;
  contact_person?: string | null;
  contact_phone?: string | null;
  contact_email?: string | null;
};

// Type for testimonials
export type Testimonial = {
  id: string;
  name: string;
  avatar_url?: string;
  testimonial: string;
  rating: number;
  position?: string;
  company?: string;
  created_at: string;
};

// Type for inquiries
export type Inquiry = {
  id: string;
  user_id?: string;
  property_id?: string;
  name: string;
  email: string;
  phone?: string;
  message: string;
  status: string;
  created_at: string;
  updated_at: string;
};
